name: backfill-last-365-days
on:
  workflow_dispatch:        # run manually from Actions tab
    inputs:
      target_date:             # <-- add this block if not present
        description: "YYYY-MM-DD (single day). Leave blank for default behaviour"
        required: false
        type: string

jobs:
  backfill:
    runs-on: ubuntu-latest
    env:                     # inject the same secrets the nightly jobs use
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      BUCKET:                ${{ secrets.BUCKET }}
      SOCRATA_APP_TOKEN:     ${{ secrets.SOCRATA_APP_TOKEN }}
      ATHENA_WORKGROUP_NAME: ${{ secrets.ATHENA_WORKGROUP_NAME }}
      TARGET_DATE: ${{ inputs.target_date }}   # <-- pass to extractor
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}

      - run: pip install -r requirements.txt

      - name: Run extractors for the last 365 days
        run: |
          for i in {15..27}; do
            TARGET_DATE="2024-09-$(printf "%02d" $i)"
            echo ">>> $TARGET_DATE"
            export TARGET_DATE
            python data_ingest/fetch_buf_biz.py
            # python data_ingest/fetch_buf_crime.py
            # python data_ingest/fetch_buf_permits.py
            # python data_ingest/fetch_buf_viol.py
            # python data_ingest/fetch_buf_311.py
            sleep 2        # polite pause → ~30 min total extra
          done

      - name: Repair partitions
        run: |
          for tbl in raw_buf_crime raw_buf_viol raw_buf_permits raw_buf_biz raw_buf_311; do
            aws athena start-query-execution \
              --work-group "$ATHENA_WORKGROUP_NAME" \
              --query-string "MSCK REPAIR TABLE civic_pulse.${tbl};"
          done