name: ingest-crime
on:
  schedule: [{ cron: "23 4 * * *" }]      # nightly 04:23 UTC
  workflow_dispatch:
jobs:
  pull:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUCKET: ${{ secrets.BUCKET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install pandas pyarrow boto3 requests
      - run: python data_ingest/fetch_crime.py
