name: ingest-crime

on:
  # schedule:
  #   - cron: '23 4 * * *'          # nightly
  workflow_dispatch:              # manual trigger

jobs:
  ingest_and_register:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      BUCKET:                ${{ secrets.BUCKET }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install pandas pyarrow boto3 requests

      - name: Fetch crime parquet
        run: python data_ingest/fetch_crime.py

      - name: MSCK crime
        run: |
          aws athena start-query-execution \
            --work-group civic_pulse \
            --query-string "MSCK REPAIR TABLE civic_pulse.raw_crime;"
